SUBCATE_GROUP: 
  DR:
    AE:
      PRIMARY_DOMAIN: DR
      SECONDARY_DOMAIN: AE
      PRIMARY_ID_COLUMN: ECAENO
      SECONDARY_ID_COLUMN: AESPID
      CATE_WITH_SECONDARY_MATCH: ['DRAE0', 'DRAE4', 'DRAE5', 'DRAE6', 'DRAE7', 'DRAE8', 'DRAE9'] 
      CATE_WITHOUT_SECONDARY_MATCH: ['DRAE1', 'DRAE2'] #ae_noids

    OV:
      PRIMARY_DOMAIN: DR
      SECONDARY_DOMAIN: DR
      PRIMARY_ID_COLUMN: ECAENO
      SECONDARY_ID_COLUMN: ECAENO
      CATE_WITHOUT_SECONDARY: [DROV1, DROV2]

FIELDS_FOR_UI:
  BASIC: [STUDYID, SITEID, SUBJID, SUBJECTID, VISITID, VISITINDEX, ITEMSETIDX, FORMID, FORMIDX, FORMINDEX, MODIF_DTS]
  DRAE0:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECADJO, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR,AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE1:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSTOT,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO,ECPDOSE,ECDOSU]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE2:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSTOT,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO, ECPDOSE, ECDOSU]
  DRAE4:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSTOT, ECPDOSE, ECDOSU, ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE5:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSTOT, ECPDOSE, ECDOSU, ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE6:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSTOT, ECPDOSE, ECDOSU, ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE7:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECDOSTOT,  ECDOSU, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE8:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECDOSTOT,  ECDOSU, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE9:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECDOSTOT,  ECDOSU, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DROV1:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECDOSTOT, ECDOSU, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSADJ, ECADJ, ECADJO, ECAENO,CDR_SKEY] # removing lowercase 'cdr_skey'
  DROV2:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECSTTIME, ECENDTIME, ECDOSTOT, ECDOSU, ECPDOSE, ECPDOSEU, ECPDFRQ, ECDOSADJ, ECADJ, ECADJO, ECAENO,CDR_SKEY] # removing lowercase 'cdr_skey'
  DROV:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECDOSTOT,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
  
FIELD_NAME_DICT:
  #EC
  ECDOSADJ: Was the Dose adjusted for planned
  ECADJ: Reason for dose adjusted
  ECADJO: If other, specify
  ECPDOSE: Planned Dose
  ECPDFRQ: Planned Dose Frequency
  ECTRT: Treatment Name
  ECDOSTOT: Total Dose
  ECDOSU: Dose Unit
  ECSTDAT: Dose Start Date
  ECENDAT: Dose End Date
  ECSTTIME: Start Time
  ECENDTIME: End Time
  ECPDOSEU: Planned Dose Unit
  ECAENO: AE Identifier
  EC_ITEMSETIDX: Dose Record Number
  EC_VISITNAM: Dose Visit
  EC_FORMNAME: Dose Form Name
  CDR_SKEY: INTERNAL ID

  ECDOSADJ_1: Was the Dose adjusted from planned
  ECADJ_1: Reason for dose adjusted
  ECADJO_1: If other, specify
  ECPDOSE_1: Planned Dose
  ECPDFRQ_1: Planned Dose Frequency
  ECTRT_1: Treatment Name
  ECDOSTOT_1: Total Dose
  ECDOSU: Total Dose Unit
  ECSTDAT_1: Dose Start Date
  ECENDAT_1: Dose End Date
  ECPDOSEU: Planned Dose Unit
  ECAENO_1: AE Identifier
  EC_ITEMSETIDX_1: Dose Record Number
  EC_VISITNAM_1: Dose Visit
  EC_FORMNAME_1: Dose Form Name
  
  #AE
  AESPID: AE Identifier
  AETERM: AE Term
  AESTDAT: AE Start Date
  AEENDAT: AE End Date
  AEONGO: AE Ongoing
  AETOXGR: AE Toxicity grade
  AEACN: Action taken with treatment
  AEACN1: Action taken with treatment 1
  AEACN2: Action taken with treatment 2
  AEACN3: Action taken with treatment 3
  AEACN4: Action taken with treatment 4
  AEACN5: Action taken with treatment 5
  AEACN6: Action taken with treatment 6
  AEREL: Event Related to treatment
  AEREL1: Event Related to treatment 1
  AEREL2: Event Related to treatment 2
  AEREL3: Event Related to treatment 3
  AEREL4: Event Related to treatment 4
  AEREL5: Event Related to treatment 5
  AEREL6: Event Related to treatment 6
  AEDECOD: Dictionary coded term
  AECMGIV: Was a Concomitant Medication given?