SUBCATE_GROUP: 
  AE:
    CM:
      PRIMARY_DOMAIN: AE
      SECONDARY_DOMAIN: CM
      PRIMARY_ID_COLUMN: AESPID
      SECONDARY_ID_COLUMN: CMAENO
      CATE_WITH_SECONDARY_MATCH: [AECM0,AECM1, AECM2, AECM3, AECM4, AECM5, AECM6,
            AECM7, AECM1_1, AECM2_1]
      CATE_WITHOUT_SECONDARY_MATCH: [AECM8]
    
    OV:
      PRIMARY_DOMAIN: AE
      SECONDARY_DOMAIN: AE
      PRIMARY_ID_COLUMN: AESPID
      SECONDARY_ID_COLUMN: AESPID
      CATE_WITHOUT_SECONDARY: [AEOV1 , AEOV2]

    DR:
      PRIMARY_DOMAIN: AE
      SECONDARY_DOMAIN: DR
      PRIMARY_ID_COLUMN: AESPID
      SECONDARY_ID_COLUMN: ECAENO
      CATE_WITH_SECONDARY_MATCH: [AEDR0]
      CATE_WITHOUT_SECONDARY_MATCH:  [AEDR1, AEDR2]
      CATE_WITH_OTHERS: [AEDR3, AEDR6, AEDR7, AEDR8, AEDR10]
  CM:
    AE:
      PRIMARY_DOMAIN: CM
      SECONDARY_DOMAIN: AE
      PRIMARY_ID_COLUMN: CMAENO
      SECONDARY_ID_COLUMN: AESPID
      CATE_WITH_SECONDARY_MATCH: [CMAE0, CMAE1, CMAE2, CMAE3, CMAE7, CMAE8, CMAE1_1, CMAE2_1]
      CATE_WITHOUT_SECONDARY_MATCH: [CMAE0, CMAE5, CMAE6]
    OV:
      PRIMARY_DOMAIN: CM
      SECONDARY_DOMAIN: CM
      PRIMARY_ID_COLUMN: CMAENO
      SECONDARY_ID_COLUMN: CMAENO
      CATE_WITHOUT_SECONDARY: [CMOV1, CMOV2]

  DR:
    AE:
      PRIMARY_DOMAIN: DR
      SECONDARY_DOMAIN: AE
      PRIMARY_ID_COLUMN: ECAENO
      SECONDARY_ID_COLUMN: AESPID
      CATE_WITH_SECONDARY_MATCH: ['DRAE0', 'DRAE4', 'DRAE5', 'DRAE6', 'DRAE7', 'DRAE8', 'DRAE9'] 
      CATE_WITHOUT_SECONDARY_MATCH: ['DRAE1', 'DRAE2'] #ae_noids

    OV:
      PRIMARY_DOMAIN: DR
      SECONDARY_DOMAIN: DR
      PRIMARY_ID_COLUMN: ECAENO
      SECONDARY_ID_COLUMN: ECAENO
      CATE_WITHOUT_SECONDARY: [DROV1, DROV2]

FIELDS_FOR_UI:
  BASIC: [STUDYID, SITEID, SUBJID, SUBJECTID, VISITID, VISITINDEX, VISITIDX, ITEMSETIDX, FORMID, FORMIDX, FORMINDEX, MODIFYTS, DATEDATECHANGED, ITEMSETIDX]
  AECM0:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
  AECM1:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CMSPID, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMAER, CMAENO]
  AECM2:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AECMGIV,AETOXGR]
    CM: [CMTRT, CMSPID, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMAER, CMAENO,CMONGO]
  AECM1_1:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV, AECMGIV]
    CM: [CMTRT, CMSPID, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
  AECM2_1:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV, AECMGIV]
    CM: [CMTRT, CMSPID, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
  AECM3:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE, CMONGO, CMAER, CMAENO]  ## NEED TO CHECK FOR DOSING
  AECM4:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE, CMONGO, CMAER, CMAENO, CMSPID]  ## NEED TO CHECK FOR DOSING
  AECM5:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO, CMSPID]
  AECM6:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
  AECM7:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE, CMAER, CMAENO]  ## NEED TO CHECK FOR DOSING
  AECM8:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AETOXGR, AECMGIV]
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO, CMSPID]
  AEOV1:
    AE: [FORMIDX, AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    CM: []
  AEOV2:
    AE: [FORMIDX, AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    CM: []
  AEOV3:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    CM: []
  AEOV1_1:
    AE: [FORMIDX, AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV]
  AEOV2_1:
    AE: [FORMIDX, AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV]
  AEOV3_1:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV]
  AEDR0:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR1:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR2:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR3:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
#     EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR4:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR5:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6] 
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR6:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR7:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6] #removing the  AETOXGR,
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR8:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  AEDR10:
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
    EC: [itemset_ix, visit_nm, formname, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECPDOSE,  ECPDOSEU, ECDOSTOT, ECDOSU, ECDOSADJ, ECADJ, ECAENO]
  
  CMAE0:
    CM: [CMSPID, CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
  CMAE1:
    CM: [CMTRT, CMSPID, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE2:
    CM: [CMTRT, CMSPID, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE1_1:
    CM: [CMTRT, CMSPID, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV, AECMGIV]
  CMAE2_1:
    CM: [CMTRT, CMSPID, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AESEV, AECMGIV]
  CMAE3:
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE, CMONGO, CMAER, CMAENO, CMSPID]    ## NEED TO CHECK FOR DOSING
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE4:
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO, CMSPID]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE5:
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO, CMSPID]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE6:
    CM: [CMTRT, CMSPID, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
  CMAE7:
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMONGO, CMAER, CMAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMAE8:
    CM: [CMTRT, CM_FORMIDX, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE, CMONGO, CMAER, CMAENO, CMSPID] ## NEED TO CHECK FOR DOSING
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR, AECMGIV]
  CMOV1:
    CM: [FORMIDX, CMSPID, CMTRT, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDSTXT, CMDOSU, CMDOSFRQ, CMROUTE, CMONGO, CMAER]  ## NEED TO CHECK FOR DOSING
    AE: []
  CMOV2:
    CM: [FORMIDX, CMSPID, CMTRT, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDSTXT, CMDOSU, CMDOSFRQ, CMROUTE,  CMONGO, CMAER]  ## NEED TO CHECK FOR DOSING
#     CM: [FORMIDX, CMSPID, CMTRT, CMDECOD, CMSTDAT, CMENDAT, CMDOSTOT, CMDOSU, CMDOSFRQ, CMROUTE,  CMONGO, CMAER, CMAENO]
    AE: []
  
  AELB0:
    AE: [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    LB: [visit_nm, formname, LBSTAT, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU]
  AELB1:
    AE: [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    LB: [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU]
  AELB2:
    AE: [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    LB: [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU]
  AELB3:
    AE: [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    LB: [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU]
  AELB4:
    AE: [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
    LB: [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU, grade]

  LBAE0:
    LB : [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU]
    AE : [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
  LBAE1:
    LB : [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU, grade]
    AE : [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
  LBAE2:
    LB : [visit_nm, formname, LBTEST, LBDAT, LNMTLOW, LBORRES, LNMTHIGH, LNMTUNIT, LBORRESU, grade]
    AE : [AESPID, AEDECOD, AESTDAT, AEENDAT, AEONGO, AETOXGR]
  LBOV1:
    LB1: [visit_nm, LBTEST, LBDAT, LBTIM, LBORRES, LNMTUNIT, LBORRESU,cdr_skey]
    LB2: [visit_nm, LBTEST, LBDAT, LBTIM, LBORRES, LNMTUNIT, LBORRESU,cdr_skey]

  DRAE0:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECADJO, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE1:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE2:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
  DRAE4:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE5:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE6:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE7:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE8:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DRAE9:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO]
    AE: [AETERM, AESPID, AEDECOD, AESTDAT, AEENDAT, AEENDAT, AEONGO, AETOXGR, AEACN, AEACN1, AEACN2, AEACN3, AEACN4, AEACN5, AEACN6, AEREL, AEREL1, AEREL2, AEREL3, AEREL4, AEREL5, AEREL6]
  DROV1:
    EC: [EC_MODIFYTS, EC_DATEDATECHANGED, EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO,CDR_SKEY]
  DROV2:
    EC: [EC_MODIFYTS, EC_DATEDATECHANGED, EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO,CDR_SKEY]
  DROV:
    EC: [EC_ITEMSETIDX, EC_VISITNAM, EC_FORMNAME, ECTRT, ECSTDAT, ECENDAT, ECPDFRQ, ECDOSE,  ECPDOSEU, ECDOSADJ, ECADJ, ECAENO,CDR_SKEY]
  
FIELD_NAME_DICT:
  #AE
  AESPID: AE Identifier
  AETERM: AE Term
  AESTDAT: AE Start Date
  AEENDAT: AE End Date
  AEONGO: AE Ongoing
  AETOXGR: Toxicity grade
  AEACN: Action taken with treatment
  AEACN1: Action taken with treatment 1
  AEACN2: Action taken with treatment 2
  AEACN3: Action taken with treatment 3
  AEACN4: Action taken with treatment 4
  AEACN5: Action taken with treatment 5
  AEACN6: Action taken with treatment 6
  AEREL: Event Related to treatment
  AEREL1: Is the Event Related to treatment 1?
  AEREL2: Is the Event Related to treatment 2? 
  AEREL3: Is the Event Related to treatment 3?
  AEREL4: Is the Event Related to treatment 4?
  AEREL5: Is the Event Related to treatment 5?
  AEREL6: Is the Event Related to treatment 6?
  AEDECOD: Dictionary coded term
  AECMGIV: Was a Concomitant Medication given?
  AESEV: Severity

  #CM
  CMSPID: CM Identifier
  CMTRT: CM Term
  CMDECOD: Standardized Medication Name
  CMSTDAT: CM Start date
  CMENDAT: CM End date
  CMONGO: CM Ongoing
  CMAENO: AE Identifier
  CMAER: Was this medication given to treat an Adverse Event?
  CMDOSTOT: Dose
  CMDOSU: Dose Unit
  CMDOSFRQ: Dose Frequency
  CMROUTE: Dose route
  CMDSTXT: DOSE

  #EC
  ECADJ: What was the reason the dose was adjusted ?
  ECPDFRQ: Planned Dose Frequency
  ECTRT: Treatment Name
  ECDOSE: Total Dose
  ECSTDAT: Dose Start Date
  ECENDAT: Dose End Date
  ECAENO: EC AE Identifier
  itemset_ix: Dose Record Number
  ECPDOSE: Planned Dose
  ECPDOSEU: Planned Dose Unit
  ECPDFRQ: Planned Dose Frequency
  ECDOSTOT: Total Dose
  ECDOSU: Total Dose Unit
  ECDOSADJ: Was the dose adjusted from planned ?
  CDR_SKEY: INTERNAL ID
  
  #LB
  grade: CTCAE Grade
  visit_nm: Visit Name
  formname: Form Name
  LBDAT: Date of Specimen Collection
  LBTIM: Time of Specimen Collection
  LBTEST: Lab Test
  LBORRES: Result
  LBORRESU: Original Units
  cdr_skey: INTERNAL ID
